In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv(r"c:\Users\nabee\Downloads\email_spam_dataset.csv")
df

                                            email_text label
0            Here is the project update you asked for.   ham
1       Limited offer!!! Buy now and get 50% discount.  spam
2    Win cash prizes instantly by replying to this ...  spam
3    Urgent! Your account has been suspended. Verif...  spam
4         Hi, please find the meeting agenda attached.   ham
..                                                 ...   ...
315          Here is the project update you asked for.   ham
316   You are selected for a free gift card. Act fast.  spam
317  Win cash prizes instantly by replying to this ...  spam
318     Limited offer!!! Buy now and get 50% discount.  spam
319  Congratulations! You have won a free lottery. ...  spam

[320 rows x 2 columns]

In [3]:
df.head(5)

                                          email_text label
0          Here is the project update you asked for.   ham
1     Limited offer!!! Buy now and get 50% discount.  spam
2  Win cash prizes instantly by replying to this ...  spam
3  Urgent! Your account has been suspended. Verif...  spam
4       Hi, please find the meeting agenda attached.   ham

In [4]:
df.columns

Index(['email_text', 'label'], dtype='object')

In [5]:
# df['label']=df['label'].map({'ham':0,'spam':1})

In [6]:
# x=df['email_text']
# y=df['label']

In [7]:
# from sklearn.model_selection import train_test_split

In [8]:
# x_train,x_test,y_train,y_text=train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
# from sklearn.feature_extraction.text import CountVectorizer

In [10]:
# vectorizer= CountVectorizer(stop_words='english')
# x_train_vec=vectorizer.fit_transform(x_train)
# x_test_vec=vectorizer.transform(x_test)

In [11]:
# from sklearn.naive_bayes import MultinomialNB

# model=MultinomialNB()
# model.fit(x_train_vec,y_train)

In [12]:
# y_pred=model.predict(x_test_vec)

In [13]:
# from sklearn.metrics import accuracy_score,classification_report

In [14]:
# print(accuracy_score(y_text,y_pred))

In [15]:
# x_train.head(4)

In [16]:
# new_email=[' Win cash prizes instantly by replying to this ...']
# new_vec=vectorizer.transform(new_email)
# print(model.predict(new_vec))